### ISSUE TITLE
Update to bamboo 0.5.7

### ISSUE THREAD

**Issue by rgaudin** [SEL-Columbia/pybamboo#12]
released version 0.5.4
- <del>create a dataset from a JSON file, in the same format bamboo exports data as JSON.</del>
  - <del>can pass json_file to POST datasets</del>
- <del>schema and JSON or CSV file can be posted in the same call, http://bamboo.io/docs/advanced_commands.html#create-a-dataset-with-data-from-a-schema</del>
- <del>grouping on dates using pandas resample function, http://bamboo.io/docs/advanced_commands.html#resampling-a-dataset</del>
  - <del>new endpoint GET dataset/resample</del>
- <del>calculate rolling statistics, like rolling mean, http://bamboo.io/docs/advanced_commands.html#calculating-rolling-statistics</del>
  - <del>new endpoint dataset/rolling, takes win_type and window params</del>
- <del>users can set/update the label, description, license, and attribution per dataset, http://bamboo.io/docs/advanced_commands.html#updating-dataset-metadata</del>
  - <del>new endpoint PUT datasets/[ID]/info</del>

Full list of closed issues: https://github.com/modilabs/bamboo/issues?milestone=13&state=closed

Next up is the 0.6 milestone, https://github.com/modilabs/bamboo/issues?milestone=6&page=1&state=open, the included issues will be adjusted a bit.

**Comment by mejymejy** [comment]
bumped to 0.5.5
- disallow calculations with the same name
- disallow aggregations with the same name in the same group
- allow join on different columns
  - POST datasets/join "on" parameter specifies this, http://bamboo.io/docs/advanced_commands.html#joining-on-different-columns
- add count command
  - GET datasets/[ID] can take "count" parameter, http://bamboo.io/docs/basic_commands.html#only-return-the-count
- split server setup and contributing code out of README, http://bamboo.io/docs/index.html#server-setup-and-contributing-code
- attempt to recover oversize saves by reducing batch size
- upgrade celery to 3.0.13
  - remove nested async calls (they may cause problems)
  - ignore returns results on async calls where appropriate
  - set celery module in project init so it doesn't depend on imports
- upgrade scipy to 0.11
- refactoring import functions, abstract model
- store error message on dataset import failure (needs more testing and inclusion for other failures)

**Comment by rgaudin** [comment]
can now pass a mapping when merging datasets, for aligning columns, e.g. foodtype and food_type
new parameter mapping for /datasets/merge
batch calculation uploads now calculated in batches
put bamboo under monit on server, checked in the monit scripts, /deply/monit

**Comment by rgaudin** [comment]
**Cross off list** (`update_to_0.5.5` branch)
- create a dataset from a JSON file, in the same format bamboo exports data as JSON. can pass json_file to POST datasets. bdd2623
- schema and JSON or CSV file can be posted in the same call. a303111

**Comment by mejymejy** [comment]
one strange thing that i have noticed:

bamboo is at version 0.5.6 and pybamboo is at 0.5.7.x

obviously we want to keep these in sync and once bamboo hits 0.5.7 we should be ok (do we just bump from master sometime soon?).  side note: @rgaudin thank you for consolidating the version in bamboo.  will make things so much easier!

i think we can avoid this in the future by using the x in the above pybamboo (0.5.7.x) version to make updates to the code for that version of bamboo (0.5.7).  one question is how we want to update the minor version of pybamboo (the 7).  do we want to only bump to 0.5.7 when all the functionality of bamboo version 0.5.7 is complete?  i think that this makes sense...

for example:

say bamboo is at 0.5.5 and pybamboo is up to date at 0.5.5.9 and then bamboo updates to 0.5.6

what do we do?

we make a milestone called 0.5.6 where we list all of the changes (read: create issues for them) to pybamboo that need to happen to make it compliant with bamboo 0.5.6 and then only bump pybamboo to 0.5.6 when we have completed that milestone.  in the interim we keep working on 0.5.5.x

this way we can still increment the pybamboo version while maintaining a sane/semantic relation to the bamboo version that it supports.

**Comment by mejymejy** [comment]
one part that i may have left out is that this library is still in relatively early development and i think that it might make sense to only count those API changes that affect _current functionality_ not full implementation of the API.

that is, say in the new bamboo version we change the URL for creating a dataset and add a new URL endpoint for making cookies.  the main question is whether we should  bump pybamboo to the new version of bamboo once we have accommodated the change to the dataset endpoint or whether we should wait until we support add_cookies in pybamboo as well...

as i said, i think it might make sense to go with the former option since the pybamboo version should reflect that the current functionality of pybamboo works with the corresponding version of bamboo whilst still potentially lacking certain functionality which can be added at any point.  this way our lack of complete implementation doesn't hold us back from keeping our versioning up to date.

**Comment by pld** [comment]
+1

**Comment by rgaudin** [comment]
OK,

I think we're all on the same page, which is:
- bamboo version is `0.5.6` 
- pybamboo becomes `0.5.6.x` once all the `bamboo 0.5.6` features has been implemented.
- pybamboo `.x` refers to internal iterations (bug fixes obviously)
- once bamboo release `0.5.7`, we can start a pybamboo `0.5.7` branch and work on it while maintaining the master.

That sounds all very logic to me, from a user's perspective. What do you think?

**Comment by rgaudin** [comment]
Bamboo 0.5.7
- finally fix travis for bamboo
  - downgraded SciPy to 0.9.0 (since that is what pandas uses in their travis and there is a deb binary for it)
  - bamboo devs, please run: pip install -r requirements.pip
- <del>add query parameter to resample function</del>
  - <del>API addition, /resample may take query, http://bamboo.io/docs/advanced_commands.html#timeseries-operations-on-a-dataset</del>
- can use a list of groups in JSON calculations
  - see format change here, http://bamboo.io/docs/advanced_commands.html#replicating-a-calculation-across-groups
  - JSON format change: in calculations use "groups" key instead of previous "group" key
- option to get index for dataset,
  - API addition, /datasets/[ID] can take an index parameter, if passed the returned dataset will have an index for each row, http://bamboo.io/docs/advanced_commands.html#additional-dataset-query-parameters
- add show, edit, and delete based on index (this is alpha quality, so for now use with caution)
  - API addition, http://bamboo.io/docs/manipulating_data.html#modifying-your-data
- parent IDs returned on dataset/info call
  - a dataset can have many parents, we can see how useful this is and figure out how to modify it going forward

**Comment by rgaudin** [comment]
Progress: PR https://github.com/modilabs/pybamboo/pull/22
- grouping on dates using pandas resample function, http://bamboo.io/docs/advanced_commands.html#resampling-a-dataset
  - new endpoint GET dataset/resample
- add query parameter to resample function
  - API addition, /resample may take query, http://bamboo.io/docs/advanced_commands.html#timeseries-operations-on-a-dataset

**Comment by rgaudin** [comment]
Now updated to **0.5.5**

TODO up-to **0.5.7**:
- can use a list of groups in JSON calculations
  - see format change here, http://bamboo.io/docs/advanced_commands.html#replicating-a-calculation-across-groups
  - JSON format change: in calculations use "groups" key instead of previous "group" key
- <del>option to get index for dataset,</del>
  - <del>API addition, /datasets/[ID] can take an index parameter, if passed the returned dataset will have an index for each row, http://bamboo.io/docs/advanced_commands.html#additional-dataset-query-parameters</del>
- <del>add show, edit, and delete based on index (this is alpha quality, so for now use with caution)</del>
  - <del>API addition, http://bamboo.io/docs/manipulating_data.html#modifying-your-data</del>

**Comment by rgaudin** [comment]
Completed.

Please take a look at [pull-request 27](https://github.com/modilabs/pybamboo/pull/27) then we'll just have to bump the version to `0.5.7.1`

**Comment by mejymejy** [comment]
merged. closing.
